### ISSUE TITLE
improving precision of event rasters

### ISSUE THREAD

**Issue by neuromusic** [KordingLab/spykes#43]
The method of generating the rasters strikes me as incredibly imprecise. Please correct me if my understanding of the algorithm is wrong.

We create a single `bins` vector that spans the spiketimes, then...

``` Python
# bin the spikes into time bins
spike_counts = np.histogram(self.spiketimes, bins)[0]

# bin the events into time bins
event_counts = np.histogram(selected_events, bins)[0]
event_bins = np.where(event_counts > 0)[0]

raster = np.array([(spike_counts[(i+window[0]/binsize): \
                                 (i+window[1]/binsize+1)]) \
                   for i in event_bins])
```

Spikes AND events are binned in this vector and the raster is built from the counts aligned to the bins that contain events.

This approach means that any spike that lands in the same bin as the event is counted in that bin, no matter whether it occurred before the event of after.

Further, if events are not regular, then sometimes the event will happen early in the bin and the bin will consist mostly of spikes that happen after the event and other times, visa versa.

I expected that a unique `bins` vector would be constructed for each event, spanning the window so that spikes were clearly assigned before or after the event.

**Comment by pavanramkumar** [comment]
That seems, right: `bins` should be constructed within a loop for each event. This will be bad for large bin sizes. Let me check with @hugoguh
