### ISSUE TITLE
fix numba dependency

### ISSUE THREAD

**Issue by timshell** [KordingLab/spykes#58]
The `from numba.decorators import autojit`in neuropop.py makes an error if the user doesn't have numba installed

The README states its not a dependency but rather for optimization.

Thus, two potential solutions are

1. It should be considered a dependency and reflect that in the README
2. try importing it if it exists (see: http://stackoverflow.com/questions/5847934/how-to-check-if-python-module-exists-and-can-be-imported)

**Comment by pavanramkumar** [comment]
Thanks! Probably the simplest fix is to edit the wording in the README

**Comment by timshell** [comment]
ditto for matplotlib

**Comment by pavanramkumar** [comment]
addressed now: a8a12b1cbcc65ee8153eecaae1510b74f6401ef0
